# CircleCI configuration file

version: 2.1

parameters:
  project-folder:
    type: string
    default: "avizio_database"
  pylint-threshold:
    type: string
    default: "6"
commands:
  poetry-setup:
    description: Private repository pull
    steps:
      - run: |
          curl -sSL https://install.python-poetry.org | python3 - --uninstall
          curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
  python-install-dev:
    description: Install dev dependencies
    steps:
      - run: |
          poetry install
  python-install-no-dev:
    description: Install dependencies
    steps:
      - run: poetry install --no-dev --no-root
  python-build:
    description: Install dependencies
    steps:
      - run: poetry build
  python-pylint:
    description: Pylint
    steps:
      - run: poetry run pylint --fail-under=<<pipeline.parameters.pylint-threshold>> **/*.py
  python-test:
    description: Test execution
    steps:
      - run: poetry run pytest
  python-report:
    description: Test report
    steps:
      - run: poetry run coverage run --source <<pipeline.parameters.project-folder>>/ -m pytest tests --cov=<<pipeline.parameters.project-folder>> --junitxml ./coverage/reports/xunit.xml --cov-report xml:./coverage/reports/coverage.xml --html=./coverage/unit-test/index.html --self-contained-html --cov-report html:./coverage -p no:warnings -o log_cli=true
      - store_test_results:
          path: ./coverage/reports
      - store_artifacts:
          path: ./coverage